### PR TITLE
Babelify so it can be used in AWS Lambda (v6.10) right away

### PR DESCRIPTION
**Pull request by smoll**
This should address the issue I encountered in https://github.com/Kikobeats/aws-lambda-chrome/issues/3#issuecomment-370425821 for the next release of this package

### CODE REVIEW

**Comment by smoll** [comment]
I completely understand where you're coming from. Thanks for pointing out that section in the readme, I totally glazed over it.

I might be able to chat with you one-on-one if I have some time later this week, but for now I hope I can still communicate async with you.

Do you have a suggested workaround for this, when I attempt to install your package inside a docker-lambda container?

```sh
Step 9/11 : RUN yarn --ignore-engines
 ---> Running in 3876cd696064
yarn install v1.5.1
warning package.json: No license field
warning No license field
[1/4] Resolving packages...
[2/4] Fetching packages...
info fsevents@1.1.3: The platform "linux" is incompatible with this module.
info "fsevents@1.1.3" is an optional dependency and failed compatibility check. Excluding it from installation.
[3/4] Linking dependencies...
[4/4] Building fresh packages...
error An unexpected error occurred: "/var/task/node_modules/is-tracking-domain: Command failed.
Exit code: 1
Command: sh
Arguments: -c curl -sL https://rawgit.com/disconnectme/disconnect-tracking-protection/master/services.json | ./scripts/postinstall
Directory: /var/task/node_modules/is-tracking-domain
Output:
/var/task/node_modules/is-tracking-domain/scripts/postinstall:9
;(async() => {
       ^
SyntaxError: Unexpected token (
    at createScript (vm.js:56:10)
    at Object.runInThisContext (vm.js:97:10)
    at Module._compile (module.js:542:28)
    at Object.Module._extensions..js (module.js:579:10)
    at Module.load (module.js:487:32)
    at tryModuleLoad (module.js:446:12)
    at Function.Module._load (module.js:438:3)
    at Module.runMain (module.js:604:10)
    at run (bootstrap_node.js:390:7)
    at startup (bootstrap_node.js:150:9)".
```

This is my Dockerfile:

```Dockerfile
FROM lambci/lambda:build-nodejs6.10

ENV CODE_HOME /var/task
WORKDIR $CODE_HOME

RUN curl --silent --location https://dl.yarnpkg.com/rpm/yarn.repo | tee /etc/yum.repos.d/yarn.repo
RUN yum clean all && \
   yum -y install yarn

COPY package.json $CODE_HOME/
COPY yarn.lock $CODE_HOME/
RUN yarn --ignore-engines

COPY . $CODE_HOME/
CMD ["bash"]
```

**Comment by Kikobeats** [comment]
the `async` feature is available for node > 6, this is why the process throw an error.

Actually no idea about docker and lambda. My point is that you can use a high node version and then ship the node binary with your lambda code

**Comment by tomgallagher** [comment]
I'm keen to try this but I'm a bit low-powered when it comes to unix shell scripts. Seems like AWS should be supporting more up-to-date versions of Node.

**Comment by smoll** [comment]
The main problem is that you require a higher Node version just to run npm install, not even to run the actual files. A possible solution is to simply use a different Dockerfile or customize Lambda-docker to the point that npm install references a different Node binary but at that point you might as well just use a different Docker image.

**Comment by tomgallagher** [comment]
Node 8.1 available on Lambda as of April 2.

https://aws.amazon.com/blogs/compute/node-js-8-10-runtime-now-available-in-aws-lambda/

**Pull request closed without merging**
